### ISSUE TITLE
Possible Java Implementation and question about complexity

### ISSUE THREAD

**Issue by StoneT2000** [igushev/IgushArray#2]
Hi Igushev,

I came across your IgushArray on GitHub recently and after reading through the README, I found it really interesting on how it is able to achieve N^1/2 insertion time complexity. I'm trying to write a Java implementation of the IgushArray, however I entered a problem and have a question about the theory behind this array.

When inserting an element into a particular DEQ, I understand how that takes O(N^1/2) time, but I'm curious as to how you "move" the elements in that particular DEQ and subsequent DEQs down in O(1) time for each "move" down operation. My understanding is that you are implementing the DEQ with an array, not list, so when you move down elements, wouldn't it take O(N^1/2) time for each "move" down operation, rendering the entire insertion operation as O(N^1/2) + O(N^1/2) * O(N^1/2) = O(N), a linear operation? In other words, how is O(1) time achieved for the "move" operation when you have to push it to the beginning of a DEQ implemented with array?

Thanks

**Comment by 99991** [comment]
The deque is implemented as a circular buffer, so adding to or removing from front and back is `O(1)`.

When inserting an element into the 2-tierd array, you first find the deque where the element should be inserted. Inserting the element naively into that deque takes `O(sqrt(n))` because each deque is at most `sqrt(n)` long. If that would make the deque longer than `sqrt(n)`, take the last element of the deque and push it to the front of the next deque, which is `O(1)`. Then repeat this for all remaining `O(sqrt(n))` deques, so in total it takes `O(sqrt(n)) + O(1) + ... (sqrt(n) times) + ... + O(1) = O(sqrt(n)) + O(sqrt(n)) = O(sqrt(n))`.

Note: That's the general idea, but I have not read the code, so the details might be different here.

**Comment by StoneT2000** [comment]
@99991 Oh a circular buffer? But this circular buffer would have to be stored in a contiguous block of memory in order to achieve O(1) random access correct?

And then to perform a O(1) "move" operation, we essentially just swap one DEQ's back with another DEQ's back, and just change the index of the header which points to the header of the DEQ implemented as a circular buffer.

**Comment by 99991** [comment]
> But this circular buffer would have to be stored in a contiguous block of memory in order to achieve O(1) random access correct?

Not necessarily. For example, `std::deque` is often implemented as [several pointers to fixed-size arrays](https://stackoverflow.com/a/6292437), but I like the contiguous block of memory better because there are less pointers.

**Comment by StoneT2000** [comment]
Interesting, Java doesn't seem to have a deque implemented as a circular buffer or the way std::deque is implemented.

**Comment by igushev** [comment]
99991 explained correctly general idea.

In my C++ implementation there're a custom DEQ implementation which is based on **single** continuous in memory array, and pointer for start and end. Please refer to [`fixed_deque.h`](https://github.com/igushev/IgushArray/blob/master/src/fixed_deque.h). In Java you can use [`ArrayList`](https://docs.oracle.com/javase/6/docs/api/java/util/ArrayList.html) for that purpose.

It is very very exciting that you want to implement this structure in Java! Feel free to reach out with any questions!
